[package]
name = "webrtc"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.121"
anyhow = "1.0.52"
futures = "0.3"
tokio = { version = "1.20.0", features = ["full"] }

[dev-dependencies]
tokio-tungstenite = "0.17.2"
tungstenite = "0.17.3"
